version: '3.8'

services:
  discovery-server:
    build: ./discovery-server
    ports:
      - "8761:8761"

  config-server:
    build: ./config-server
    ports:
      - "8888:8888"
    depends_on:
      - discovery-server

  owner-service:
    build: ./owner-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server
      - config-server
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/playstore
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server
      - config-server

  notification-service:
    build: ./notification-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-server
      - config-server

  search-service:
    build: ./search-service
    ports:
      - "8084:8084"
    depends_on:
      - discovery-server
      - config-server
      - elasticsearch
    environment:
      - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=elasticsearch:9300

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server
      - config-server

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=playstore
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
