server:
  port: 8081

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: owner-service
          uri: lb://owner-service
          predicates:
            - Path=/api/owners/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: app-service
          uri: lb://app-service
          predicates:
            - Path=/apps/**
        - id: static-content
          uri: http://localhost:8081
          predicates:
            - Path=/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
